name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile C files
      run: gcc main.c add.c sub.c mul.c div.c -o calculator

    - name: Run executable with input and timeout
      run: echo -e "5\n3\n+" | timeout 10 ./calculator
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
    # Artifact name
       name: Upload
    # A file, directory or wildcard pattern that describes what to upload
       path: ${{github.workplace}}
  test:
       runs-on: ubuntu-latest
       needs: build
       steps:
       - uses: actions/checkout@v4

       - name: Compile C files
         run: gcc main.c add.c sub.c mul.c div.c -o calculator

       - name: Run executable with input and timeout
         run: echo -e "5\n3\n+" | timeout 10 ./calculator
        
