name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile C files
      run: gcc main.c add.c sub.c mul.c div.c -o calculator

    - name: Run executable
      run: ./calculator
